###register request
Post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "mehrad1",
    "email" : "mehrad1@gmail.com",
    "password" : "123456",
    "mobile" : "09100639686",
    "confirm_password" : "123456"
}
###login request
Post http://localhost:3000/auth/login
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "username" : "erfanyousefi",
    "password" : "123456"
}
--
