###create project 
post http://localhost:3000/project/create
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "title": "modalap6rojectvvvv",
    "text": "new proje6ct in indeverosity in kvvvvermansh "

}

###get All project 
GET  http://localhost:3000/project/list
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

###get project by Id
get http://localhost:3000/project/650022d82cca1f9e622e7d19
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

###remove project  by Id
delete http://localhost:3000/project/remove/65016fc1686cc8aa72ed89f1
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json


###edit project  by Id
put http://localhost:3000/project/edit/650022d82cca1f9e622e7d19
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "title": "",
    "text":"",
    "tags": ["180", "2"]
}





